# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7227bb9ac52eafde6f96592bceb77f7dd9b46c534d4ec16962567c804fa41d14e606741ae47e17b9a31858a8f558eae785a244bbacff316dedaee2eb192841ae

test:
  secret_key_base: d1e81266d8fa90e19d1ecc2d180d2ce4a402ed4d337da9377d276b65148d1dd2d09be8905fd1792340f7120093f10fbd78b3491eb0c6fbe168df13f3ec947732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
